-- create_table.sql
CREATE TABLE brand_data (
    id SERIAL PRIMARY KEY,
    brand_reason TEXT,
    problem_solving TEXT,
    core_values TEXT,
    customer_feeling TEXT,
    person_demographics TEXT,
    tone_of_voice TEXT,
    favorite_styles TEXT,
    catchphrases TEXT,
    customer_attitude TEXT,
    main_color VARCHAR(50),
    sub_color VARCHAR(50),
    accent_color VARCHAR(50),
    title_font VARCHAR(100),
    body_font VARCHAR(100),
    emphasis_font VARCHAR(100),
    image_style TEXT,
    brand_keywords TEXT,
    brand_slogan TEXT,
    sns_bio TEXT,
    brand_introduction TEXT,
    brand_philosophy TEXT,
    customer_demographics TEXT,
    customer_interests TEXT,
    customer_pains TEXT,
    expected_solutions TEXT,
    competitor_list TEXT,
    brand_differentiator TEXT,
    brand_niche_position TEXT,
    axis_x VARCHAR(100),
    axis_y VARCHAR(100),
    brand_position TEXT,
    validation_methods TEXT,
    success_metrics TEXT,
    brand_goals TEXT,
    launch_plan TEXT,
    growth_plan TEXT,
    milestones_kpis TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);